server:
  port: 8080

liquibase:
  change-log: classpath:db/db.changelog-master.xml

datasource:
  url: ${DB_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  driverClassName: org.postgresql.Driver

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  hbm2ddl-auto: none
  id_new_generator_mappings: false
  cache:
    use_query_cache: true
    use_second_level_cache: true
    factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
    ehcache:
      missing_cache_strategy: create
